/**
 * @class Program
 * @versin 0.1
 * @author Ricardo de Magalhães Simões
 * --------------------------------------------
 * @description
 */
_log("program.js", "-x-", "Starting the file execution");

class Program
{
    constructor()
    {
        this.ClassName = "Program";
        this.Name = "";
        this.User = "";

        this.Fail_Safe = new SysError("status");

        // @property {object} Server The object responsible to send the error to the 'AppServer'
        this.Server_Side = new HTTPServer();

        this.Interface = new Interface("menu", ["Home", "Options", "Report", "Help", "Sign"] );

        this.Status_Monitor = new SysStatus("status");
    }

    /******************************************************************************
     * @method Error
     * @version 0.0
     * @description Will handle the error in the system, using the class 'SysError'
     * @param {Error} [er_obj=null] Error object generated by a TRHOW or CATCH
     */
    Error( er_obj = null )
    {
        _error("PROGRAM.JS", "Error()", { param: er_obj } );

        //this.Server_Side.Send(er_obj);
    }

    /******************************************************************************
     * @method Status
     * @version 0.0
     * @description Will monitor the system status, using the class 'SysStatus'
     */
    Status()
    {
        _log("PROGRAM.JS", "Status()", { } );
        //?
    }

    /******************************************************************************
     * @method Server
     * @version 0.0
     * @description Will keep the communication with the server
     */
    Server()
    {
        _log("PROGRAM.JS", "Server()", { } );
        //?
    }

    /******************************************************************************
     * @method Main
     * @version 0.1
     * @description
     */
    Main()
    {
        try
        {
            this.Interface.Menu();
            this.Status_Monitor.Start();

            var system = _ById("system");
                system.innerHTML += "System has started<br>";
        }
        catch( er_obj )
        {
            this.Error(er_obj);
        }
    }
}
 